name: Mirror friend's repo

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror upstream
        run: |
          git clone --bare https://github.com/Ko8a/kdsfidachamp.git repo.git
          cd repo.git
          git push --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vlabeemir/KDSA2026.git
